### ISSUE TITLE
[gcloud init] (crash detected)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [binbeobo/google-cloud-sdk#309]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/surface/init.py", line 77, in Run
    if not self._PickAccount(args.console_only):
  File "googlecloudsdk/surface/init.py", line 129, in _PickAccount
    disable_user_output=False):
  File "googlecloudsdk/surface/init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/surface/auth/login.py", line 104, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/surface/auth/login.py", line 165, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
[output truncated]

```

Original issue reported on code.google.com by `car...@idea.me` on 15 Oct 2015 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. [gcloud init] essentially runs [gcloud auth login].
I assume you will get same result.

Are you behind some proxy/firewall. Can you tell what kind.

As a workaround you can run
  gcloud auth-login --no-launch-browser

Once authenticated, use [gcloud init] again and select just authenticated 
credentials.
Let us know if that worked for you.

```

Original comment by `che...@google.com` on 16 Oct 2015 at 1:04
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same problem for the past two weeks. I'm a AWS user and wanted 
to switch to Google Cloud - but this problem is stopping me.

I have Anaconda installed (python packages). But for gCloud purposes, I 
installed a fresh version of stand alone python and added it to the path (in 
the beginning). But still getting the same error when I try any gCloud init(or 
gcloud auth-login --no-launch-browser) : "ERROR: gcloud crashed 
(BadStatusLine): ''"

I'm a windows 7 user - and have no problems with the AWS CLI. PLEASE HELP!
```

Original comment by `rset...@gmail.com` on 28 Dec 2015 at 7:21

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting an issue. So when you run
  gcloud auth-login --no-launch-browser
you get URL to go to. As you copy paste the url to the browser and login you 
get a code. Once you enter the code is it then you get this error?

Also are you behind proxy/firewall ? If so do you set http_proxy environment 
variable?

Finally can you copy paste output of [gcloud info] this will help us diagnose 
the issue. 
```

Original comment by `che...@google.com` on 29 Dec 2015 at 1:40
